name: Update Data Files from Issue

on:
  issues:
    types: [opened]

jobs:
  update_data_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Issue Data and Update Files
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          # 从 Issue 中提取数据
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "$ISSUE_BODY" > issue_data.json

          # 将新数据添加到 data.json
          node -e "
          const fs = require('fs');
          const newData = require('./issue_data.json');
          const dataFilePath = './data.json';
          let data = [];
          if (fs.existsSync(dataFilePath)) {
            data = JSON.parse(fs.readFileSync(dataFilePath, 'utf8'));
          }
          data.push(newData);
          fs.writeFileSync(dataFilePath, JSON.stringify(data, null, 2));
          "

          # 生成/更新 xxxdetail.html
          node -e "
          const fs = require('fs');
          const newData = require('./issue_data.json');
          const detailsPath = './xxxdetail.html';
          const htmlContent = \`
          <html>
          <head><title>Data Detail</title></head>
          <body>
            <h1>\${newData.name}</h1>
            <p>\${newData.description}</p>
            <p><strong>Tags:</strong> \${newData.tags}</p>
          </body>
          </html>
          \`;
          fs.writeFileSync(detailsPath, htmlContent);
          "

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add data.json xxxdetail.html
          git commit -m "Update data files from new submission"
          git push
