name: Update Data Files from Issue

on:
  issues:
    types: [opened]

jobs:
  update_data_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Issue Data and Update Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 从 Issue 中获取内容并保存到 issue_data.json
          ISSUE_BODY="${{ github.event.issue.body }}"

          # 使用 printf 将 Issue 内容写入 JSON 文件
          printf '%s' "{\"issue_body\": $ISSUE_BODY}" > issue_data.json

          # 将新数据添加到 data.json
          node -e "
          const fs = require('fs');
          const newData = JSON.parse(fs.readFileSync('./issue_data.json', 'utf8')).issue_body;
          const dataFilePath = './data.json';
          let data = [];
          if (fs.existsSync(dataFilePath)) {
            data = JSON.parse(fs.readFileSync(dataFilePath, 'utf8'));
          }
          data.push(JSON.parse(newData));
          fs.writeFileSync(dataFilePath, JSON.stringify(data, null, 2));
          "

          # 生成/更新 xxxdetail.html
          node -e "
          const fs = require('fs');
          const newData = JSON.parse(fs.readFileSync('./issue_data.json', 'utf8')).issue_body;
          const detailsPath = './xxxdetail.html';
          const htmlContent = \`
          <html>
          <head><title>Data Detail</title></head>
          <body>
            <h1>Data Submission Detail</h1>
            <pre>\${newData}</pre>
          </body>
          </html>
          \`;
          fs.writeFileSync(detailsPath, htmlContent);
          "

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add data.json xxxdetail.html
          git commit -m "Update data files from new submission"
          git push
